---
kind: pipeline
type: docker
name: ReadMe
trigger:
  event:
    - push
    - pull_request

steps:
  - name: Build
    image: golang:latest
    commands:
      - cd update && go run main.go
      - git config user.name "gruberdev"
      - git config user.email "gruberdev@users.noreply.github.com"
      - git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - git add -A
      - git diff-index --quiet HEAD || git commit -m 'Update dynamic content'

  - name: Remote Update
    image: appleboy/drone-git-push
    settings:
      branch: main
      ssh_key:
        from_secret: ssh_privkey
      remote: git@github.com:gruberdev/gruberdev.git
      force: false
      commit: true
