---
kind: pipeline
type: docker
name: readme
trigger:
  event:
    include:
      - push
      - pull_request
steps:
  - name: test
    image: golang:latest
    commands:
      - cd update && go run main.go
 
