---
kind: pipeline
type: docker
name: ReadMe
trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    - main

node:
  server: home
  arm: no
  docker: yes
platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: golang:latest
    commands:
      - cd update && go run main.go
  - name: Remote Update
    image: appleboy/drone-git-push
    settings:
      branch: main
      author_name: 
        from_secret: github_user
      author_email:
        from_secret: github_email
      ssh_key:
        from_secret: ssh_privkey
      remote: git@github.com:gruberdev/gruberdev.git
      force: false
      commit: true

